### PR TITLE
Replace equality checks on sealed objects with `is` checks (fixes #129)

### LINKED ISSUE #129: kotlin.NoWhenBranchMatchedException caused by using ordinal inside of a property intiializer
Minimal reproducer
```
sealed class TestFlag {
    val i: Int = 1 shl ordinal
    @GenSealedEnum companion object
    object Foo: TestFlag()
}

fun main() {
    TestFlag.Foo.i.also(::println)
}
```
A little context about my use-case: We're using sealed classes as Flags, and so it's common for us to want each object to have an integer representation that is 1 shifted left by its ordinal.
This exception happens because during the initialization of the `INSTANCE`s for the objects, the `ordinal` extension property is accessed, which internally compares the object (using equality) against the instances of the objects inside the sealed class. A simple workaround for this is to turn `i` into a computed property, but that makes `i` get recomputed on every call, which adds the cost of all the equality checks that `ordinal` does internally.
It would be appreciated if an option in the plugin could be provided that, instead of comparing the objects by equality, does `is` checks inside the ordinal property (so that this issue is prevented). I'm not super familiar with ksp and kotlinpoet, but I can attempt at making a PR that solves this.

### PR DESCRIPTION
**Pull request by kyay10**
See #129 for the cause of the crash. This changes the code gen to do comparison checks on sealed objects using `is` instead of using equality. Also adds relevant tests.

### CODE REVIEW

**Comment by kyay10** [comment]
Some weird errors are appearing. I'll investigate and see what's happening, since I can't reproduce them locally.

**Comment by alexvanyo** [comment]
+1 to matching the constraints of an `enum class`.

I think a `lazy` with a `LazyThreadSafetyMode.PUBLICATION` sounds good for the `values` with relatively little overhead.

File: processing-tests/common/test/kotlin/com/livefront/sealedenum/compilation/equality/Flag.kt [hunk 1]
```diff
@@ -0,0 +1,120 @@
+package com.livefront.sealedenum.compilation.equality
```
Comment (alexvanyo) [inline processing-tests/common/test/kotlin/com/livefront/sealedenum/compilation/equality/Flag.kt:1]: I think placing this into `compliation/usecases` makes a lot of sense for ensuring a particular usage of `@GenSealedEnum` works!

**Comment by kyay10** [comment]
Is there any automated way to update the `fileNameGenerated` properties in the tests btw? I'm resorting to updating them manually, but with such a wide-reaching change, it takes a bit of time.

File: processing-tests/common/test/kotlin/com/livefront/sealedenum/compilation/equality/Flag.kt (hunk 1 above)
Comment (kyay10) [reply processing-tests/common/test/kotlin/com/livefront/sealedenum/compilation/equality/Flag.kt:1]: Yep, agreed. I had previously placed it there when the plan was to use a new parameter on `GenSealedEnum`, but now it's an impl detail, so it makes sense for it to be in `compilation/usecases`

**Comment by kyay10** [comment]
> I think a lazy with a LazyThreadSafetyMode.PUBLICATION sounds good for the values with relatively little overhead.

Ended up using that, and it seems to work pretty well. All tests are passing locally. Also moved the `Flag` tests to `usecases`. Hopefully, workflow tests should pass now

File: processing-common/src/main/kotlin/com/livefront/sealedenum/internal/common/spec/SealedEnumTypeSpec.kt [hunk 2]
```diff
@@ -77,8 +78,9 @@ internal data class SealedEnumTypeSpec(
 
     private fun createObjectsProperty(): PropertySpec = PropertySpec.builder("values", listOfSealedClass)
         .addModifiers(KModifier.OVERRIDE)
-        .initializer(
+        .delegate(
             buildCodeBlock {
+                beginControlFlow("lazy(mode = %T.SYNCHRONIZED)", LazyThreadSafetyMode::class.asTypeName())
```
Comment (alexvanyo) [inline processing-common/src/main/kotlin/com/livefront/sealedenum/internal/common/spec/SealedEnumTypeSpec.kt:83]: I think we should use [`LazyThreadSafetyMode.PUBLICATION`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-lazy-thread-safety-mode/-p-u-b-l-i-c-a-t-i-o-n.html#publication) here, we don't need to protect against the list being created more than once that `SYNCHRONIZED` guarantees so we can avoid the cost of synchronizing.

**Review by alexvanyo — COMMENTED** [review]
> Is there any automated way to update the *fileName*Generated properties in the tests btw? I'm resorting to updating them manually, but with such a wide-reaching change, it takes a bit of time.

Unfortunately no, I've just manually updated them as well.

File: processing-tests/common/test/kotlin/com/livefront/sealedenum/compilation/equality/Flag.kt (hunk 1 above)
Comment (alexvanyo) [reply processing-tests/common/test/kotlin/com/livefront/sealedenum/compilation/equality/Flag.kt]: Makes sense!

**Comment by kyay10** [comment]
> > Is there any automated way to update the _fileName_Generated properties in the tests btw? I'm resorting to updating them manually, but with such a wide-reaching change, it takes a bit of time.
> 
> Unfortunately no, I've just manually updated them as well.

I've opened #131 to suggest an automatic way of doing that.

**Review by alexvanyo — APPROVED** [review]
Looks great to me, thank you for the change here and the contribution!
